### ISSUE TITLE
Mohist wants to get some code authorization

### ISSUE THREAD

**Issue by CraftDream** [gnembon/carpetmod112#102]
Hello! We are writing a software for MinecraftServer ([Mohist](https://github.com/Mohist-Community/Mohist)). Your code is of good quality. We want to use some of your code. And we will put your project on the Thanks List.
Is that OK?

**Comment by Earthcomputer** [comment]
From a legal perspective, this code is licensed under LGPL, which means any code you take from this project must also be licensed with LGPL (this could be e.g. in license headers at the top of the relevant files), and those files must be open source.

From a practical perspective, I expect you could do what you like as I don't think anyone working on this project would bother to pursue it.

**Comment by CraftDream** [comment]
Thank you very much :)
