### ISSUE TITLE
Can't open shulker box, disappears when mined

### ISSUE THREAD

**Issue by KasSsa-MC** [gnembon/carpetmod112#115]
If you mine a crafting table, and place a shulker box in the same position, it can't be opened, and it disappears if you mine it. If you place a second shulker box in the same position, it works normally. If you place a bed where you had the crafting table, the part where the crafting table was, turns red. If the red part is the foot end, the bed drops as its original color. If the red part is the head end, the bed drops as a red bed.
[https://bugs.mojang.com/browse/MC-131288](url)
This bug is similar, but not exactly the same.

If you don't mine the box, go to creative mode, and pick block the box while holding ctrl, you see that only the first row of items is there. The other two rows are gone, and you can't get them back.

**Comment by Pineapplecake** [comment]
Fixed
