### ISSUE TITLE
Huge increase in tps when tick warping

### ISSUE THREAD

**Issue by TheBjoel2** [gnembon/carpetmod112#148]
When server runs normally(at 20 tps), mspt is around 20. But when we are doing /tick warp, mspt drops to 2-5. I tried to remove Thread.sleep() from the main game loop, then got 2-5 mspt. Really strange behavior

**Comment by Earthcomputer** [comment]
Does the mspt stay low once you stop tick warping again?

**Comment by TheBjoel2** [comment]
No, increases up to 20 again

**Comment by TheBjoel2** [comment]
Seems like when server running for about a day, the issue fixes itself. I don't know why and how, but when tick warping: 2-5ms, when not: 5-8ms. Really weird. Guess I'll start learning cs from scratch

**Comment by Earthcomputer** [comment]
It's probably to do with the JIT or something

**Comment by TheBjoel2** [comment]
Seems like no, because even starting up a server with -Xcomp didn't help
