### ISSUE TITLE
【Serious BUG】redstone repeater become ghost block when be placed on transparent block

### ISSUE THREAD

**Issue by HiHizhang** [gnembon/carpetmod112#174]
In the newest 1.12.2 carpet server，and all fuction closed、 when a repeater be placed on a transparent  block（like glass，stained glss or glowstone），it will apper and disapper instantly，normally consume the repeater in player's inventory。and if your gamemode is survival，the consumed repeater will come back when the next time you open a container(like a chest, or hopper). this is a serious bug,make a lot of machine cannot work normally。please fix this bug at your earliest convenience。

**Comment by HiHizhang** [comment]
The version is 22_03_22

**Comment by HiHizhang** [comment]
The version is 22_03_22

**Comment by HiHizhang** [comment]
The comparator has the same problem

**Comment by Earthcomputer** [comment]
Repeaters cannot be placed on transparent blocks in 1.12. If you are connecting to 1.12 with a newer client using multiconnect, viafabric, viaproxy or similar software, then it is a bug with that software and not carpetmod.

**Comment by HiHizhang** [comment]
clear,it is caused by forge,thanks
