### ISSUE TITLE
Command SummonPlayer not working

### ISSUE THREAD

**Issue by ghost** [gnembon/carpetmod112#22]
I believe the title is self-explanatory. Version is 18_7_31.
Tried it having it enabled or disabled incase true/false are swapped around.

**Comment by gnembon** [comment]
Yes, It has been fully replaced with /player command. In your case "/player Steve spawn", because now Steves can do other things as well.
I will leave the issue open because the commandSummonPlayer needs to be removed from config.

**Comment by ghost** [comment]
Ah ok.
Thank you

**Comment by gnembon** [comment]
removed commandSummonPlayer from settings
