### ISSUE TITLE
Consider changing the license to LGPL?

### ISSUE THREAD

**Issue by bogger33** [gnembon/carpetmod112#27]
Probably more of a theoretical concern since there don't seem to be any binary downloads anyway, but since minecraft is closed source, licensing mod code under the GPL can cause any contributor to prevent you from distributing binaries (with their code), like what happened to bukkit.

**Comment by gnembon** [comment]
True, technically with GPL Mojang woudn't be able to use portions of my code ;p. I will change it to lgpl - I see no problem with that.

**Comment by Earthcomputer** [comment]
@gnembon any update on this?

**Comment by gnembon** [comment]
should I just delete the existing one and licence selection option will magically appear in the options?

**Comment by Earthcomputer** [comment]
I don't know, but if it doesn't you can always download a copy of LGPL from the GNU website.

**Comment by lekro** [comment]
You can just replace the LICENSE file with the new text.
Just be sure to check that all contributors are ok with the license change.
