### ISSUE TITLE
missingTools fix doesn't seem to work on sponges.

### ISSUE THREAD

**Issue by Elon61** [gnembon/carpetmod112#29]
carpet mod v18_08_05

**Comment by Earthcomputer** [comment]
Are you using shears to break the sponges?

**Comment by Elon61** [comment]
oh. i was not. I completely forgot that was the tool for sponges, my apologies.
other issue with this fix: using a tool that doesn't insta-mine the block will not result in a faster mining speed, client is forge.

**Comment by gnembon** [comment]
tested with vanilla client - it mines faster, even if it is not instamine (tested on a good diamond pickaxe and pistons)
What did you try to mine and with what?

**Comment by Elon61** [comment]
i was using a normal diamond pickaxe on a piston.
Tested it on a vanilla client and on glass too, if i'm not using an enchant pickaxe fast enough so it insta-mines it doesn't work

**Comment by Earthcomputer** [comment]
Cannot reproduce
