### ISSUE TITLE
/log: Clicking unsubscribe button when already unsubscribed subscribes the user

### ISSUE THREAD

**Issue by lekro** [gnembon/carpetmod112#35]
![image](https://user-images.githubusercontent.com/1545866/44306413-ed152880-a353-11e8-931f-72fe7f48c0de.png)

Instead of toggling subscription, the "X" button should only unsubscribe a player from a logger.

**Comment by gnembon** [comment]
hmm, its initially implemented as toggle subscription. For "binary" loggers I would rather keep it as a toggle and fix in the UI so it says what it does.
I will do that, just later - I am on vacation for next 1.5 weeks.

**Comment by lekro** [comment]
:+1: enjoy your vacation!
