### ISSUE TITLE
Village Markers Freeze or dont work

### ISSUE THREAD

**Issue by Notnotkirda** [gnembon/carpetmod112#47]
When dealing with many villages, village markers will freeze and sometimes not work at all

**Comment by Earthcomputer** [comment]
What do you mean by "freeze"? Freeze the client or stay in the same place for an overly long amount of time?

**Comment by Notnotkirda** [comment]
The overlay will freeze, the client will still remain fine. Then usually after relogging or turning the overlay off after this point it will not come back on or work.

**Comment by Earthcomputer** [comment]
I imagine the fix to #5 probably affected it
