### ISSUE TITLE
/log : Being Able to Setdefaults

### ISSUE THREAD

**Issue by DeadlyMC** [gnembon/carpetmod112#53]
Setdefault feature for /log command as in /carpet setdeafult.....
As u need to type /log after every server restart, so wold be better if there was some setting to make some log rules default.....

Probably a command like:
/log setDefault [logging-option]

**Comment by Earthcomputer** [comment]
Although I agreed with this idea initially, there are two problems with this:
a) log settings are per player, which makes it a little counter-intuitive to store the settings on the server
b) the code currently doesn't make it very easy to store much except carpet rules between runs.

I think this feature might fit better into carpet client, and have some protocol between them which enables the chosen loggers on connect.

**Comment by gnembon** [comment]
Agree with earth, but from what I read from DeadlyMC maybe server owners want to have a pre-set list of loggers that they want everybody logging in to have (like tps, or mobcaps). this can be done with a server-wide (if I understand correctly)

**Comment by DeadlyMC** [comment]
Yeah gnembon that's what i was talking about :)

**Comment by angrynerd** [comment]
This sounds fun. Personally i initially thought you wanted to setdefault
for 1 player. That would get complicated with uuids and such.

**Comment by Salandora** [comment]
Has anybody tackled this yet?
If no I would like to do it. 
I would implement it like gnembon described it as a set of global loggers which everyone is subscribed to.

**Comment by skyrising** [comment]
I don't see what the problem with maintaining settings per player is.
Minecraft already does that for player files, advancements and statistics.
What would be the alternative? Everyone installing a client mod that types the `/log` commands on login?

Would be very restrictive to introduce another global setting after per-player loggers were introduced.

**Comment by Salandora** [comment]
> after per-player loggers were introduced.

Do you mean there is already a per-player logging?
Or do you suggest to go this route instead?

**Comment by skyrising** [comment]
When you do `/log <name>` it only sends that info to you, not the other players. That's what I mean with per-player logging.

**Comment by DeadlyMC** [comment]
The problem i see, is being able to store different loggers for different servers...otherwise u could just store the enabled loggers in a file and read from that file when joining a server

**Comment by Salandora** [comment]
Well I don't mind to make the list default player based.
I just thought the discussion above lead to a set of loggers which everyone is subscribed to in the first place, like a server default. 

Maybe both would be good?
1. A server owner can give a list, e.g. for new players that join, of loggers which they are subscribed to.
 This could also be just offered by a chat message on first join.

2. A player can decide on his own to change the default loggers for himself.

So what do you guys think about it?

I do like both anyway and would be very glad if I don't have to type log ... all the time after a server restart. Especially when debugging this gets annoying.

**Comment by skyrising** [comment]
I agree. One server-wide default and per-player settings for overwriting the defaults...

**Comment by Earthcomputer** [comment]
@Salandora go for it!

**Comment by DeadlyMC** [comment]
Closing this cause it was added by Salan. Thx @Salandora !
