### ISSUE TITLE
Mobile Lazy Chunk Detector not work with the pistonGhostblocksFix = clientandServer

### ISSUE THREAD

**Issue by XuedaDuan** [gnembon/carpetmod112#70]
Sorry for maybe bring you a trouble. The kind of old lazy chunk detector with the sand and observer which was showed in the Mr Eta 's video https://www.youtube.com/watch?v=LE6r-FltXHM&t=24s not work with the carpet rule pistonGhostblocksFix = clientandServer. And if pistonGhostblocksFix = true or pistonGhostblocksFix =false will not affect the machine. My version is maybe a little out of date which is V19_01_07. Also maybe this kind of result is intended with the carpet rule. If so please just ignore this issue. Thanks for you guys' hard work.

**Comment by Earthcomputer** [comment]
clientAndServer was bugged and needed removal. It's removed now.
