### ISSUE TITLE
How do I actually install this?

### ISSUE THREAD

**Issue by BlueCyro** [gnembon/carpetmod112#83]
I'm a novice, how do I go about installing this? Do I just copy the class files from the zip into a 1.12.2 server jar or what? I heard this server software is useful, but it seems like the installation outweighs the benefits.

**Comment by BlueCyro** [comment]
Nevermind, I'm just a retard and was installing it on 1.12.2. Is there a way I can let .2 clients connect?

**Comment by DeadlyMC** [comment]
There is no carpetmod for 1.12.2

**Comment by angrynerd** [comment]
There is no way to get .2 clients to connect to carpet but there is a mod
by earthcomputer to allow 1.12 to .2 servers if you would rather attempt ot
that way.

**Comment by Earthcomputer** [comment]
@RileyGuy if your players are willing to use client-side mods, they can install https://github.com/Earthcomputer/Connect-to-1-12-x on a 1.12.0 client, then they can connect to 1.12.0 and 1.12.2 servers from the same client.
It requires liteloader; the website is down but you can download it from here instead: http://repo.mumfrey.com/service/local/artifact/maven/redirect?r=snapshots&g=com.mumfrey&a=liteloader&v=1.12-SNAPSHOT&e=jar&c=release

**Comment by BlueCyro** [comment]
@Earthcomputer You're *absolutely* sure there's no possible way to get .2 clients to connect to .0 servers? It would really convenience me as there are things made for .2 that are not for .0 that I frequently use. (Just client-sided mods + a specific version of optifine that doesn't work on .0)

**Comment by Earthcomputer** [comment]
I dont know of any, sorry. Also, this is getting off topic for a carpetmod issue.
